### ISSUE TITLE
Encoded value size check is incorrect.

### ISSUE THREAD

**Issue by jmkucerak** [WickedReports/php-sdk#1]
The if statement in [WickedReports.php](https://github.com/WickedReports/php-sdk/blob/master/src/WickedReports/WickedReports.php) starting on line 203 is incorrect.  Going by the [PHP Documentation (mb_strlen)](http://php.net/manual/en/function.mb-strlen.php) the function will merely give the length of the string.  Assuming that each character is 1 byte then the comparison `mb_strlen($values) > 10240` is only checking to see if the string is 10240 bytes in length..  Since 10 megabytes contains 1000000 bytes, this comparison falls very short of the purpose of the test as indicated by `throw new ValidationException('Provided data is bigger than 10 Mbytes limit');` unless the Exception text was not meant to say 10 Mbytes.  So which is correct here, the comparison or the exception message?

**Comment by alright** [comment]
Fixed in 1.3.0
